// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PFC_VIBRANIUM_ERP.Data;

#nullable disable

namespace PFCVIBRANIUMERP.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.AcessoModel", b =>
                {
                    b.Property<int>("idUsr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsr"));

                    b.Property<int?>("funcionarioidFunc")
                        .HasColumnType("integer");

                    b.Property<int>("idFunc")
                        .HasColumnType("integer");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idUsr");

                    b.HasIndex("funcionarioidFunc");

                    b.ToTable("Acesso");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.CAPModel", b =>
                {
                    b.Property<int>("idRefCAP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRefCAP"));

                    b.Property<DateTime>("dtEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtTransacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("fornecedoridForn")
                        .HasColumnType("integer");

                    b.Property<int>("idForn")
                        .HasColumnType("integer");

                    b.Property<string>("moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("parcela")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("idRefCAP");

                    b.HasIndex("fornecedoridForn");

                    b.ToTable("CAP");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.CARModel", b =>
                {
                    b.Property<int>("idRefCAR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRefCAR"));

                    b.Property<int?>("clienteidCli")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dtEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtTransacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idCli")
                        .HasColumnType("integer");

                    b.Property<string>("moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("parcela")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("idRefCAR");

                    b.HasIndex("clienteidCli");

                    b.ToTable("CAR");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.ClienteModel", b =>
                {
                    b.Property<int>("idCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCli"));

                    b.Property<string>("agencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("conta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("enderecoidEnd")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idEnd")
                        .HasColumnType("integer");

                    b.Property<string>("idfederal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome_abrev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("razao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_recebimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idCli");

                    b.HasIndex("enderecoidEnd");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.EnderecoModel", b =>
                {
                    b.Property<int>("idEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEnd"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEnd");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.EstoqueModel", b =>
                {
                    b.Property<int>("idItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idItem"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("preco")
                        .HasColumnType("double precision");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.HasKey("idItem");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.FornecedorModel", b =>
                {
                    b.Property<int>("idForn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idForn"));

                    b.Property<string>("agencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("conta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("enderecoidEnd")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idEnd")
                        .HasColumnType("integer");

                    b.Property<string>("idfederal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome_abrev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("razao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_pagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idForn");

                    b.HasIndex("enderecoidEnd");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("idFunc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFunc"));

                    b.Property<string>("agencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("conta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dtAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dtDesligamento")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtTermino_contrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("enderecoidEnd")
                        .HasColumnType("integer");

                    b.Property<string>("forma_pagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idEnd")
                        .HasColumnType("integer");

                    b.Property<string>("nomeFuncionario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("salario")
                        .HasColumnType("double precision");

                    b.HasKey("idFunc");

                    b.HasIndex("enderecoidEnd");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.OPModel", b =>
                {
                    b.Property<int>("idOp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOp"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dtEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idProd")
                        .HasColumnType("integer");

                    b.Property<int?>("produtoidProd")
                        .HasColumnType("integer");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("roteiro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idOp");

                    b.HasIndex("produtoidProd");

                    b.ToTable("OP");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.PedidoModel", b =>
                {
                    b.Property<int>("idPed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPed"));

                    b.Property<int?>("clienteidCli")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dtPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("fornecedoridForn")
                        .HasColumnType("integer");

                    b.Property<int?>("idCli")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("idForn")
                        .HasColumnType("integer");

                    b.Property<string>("produtos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("idPed");

                    b.HasIndex("clienteidCli");

                    b.HasIndex("fornecedoridForn");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.ProdutoModel", b =>
                {
                    b.Property<int>("idProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProd"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idItem")
                        .HasColumnType("integer");

                    b.Property<int?>("itemidItem")
                        .HasColumnType("integer");

                    b.Property<string>("itens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("preco_saida")
                        .HasColumnType("double precision");

                    b.Property<double>("valor_aquisicao")
                        .HasColumnType("double precision");

                    b.HasKey("idProd");

                    b.HasIndex("itemidItem");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.AcessoModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.FuncionarioModel", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioidFunc");

                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.CAPModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.FornecedorModel", "fornecedor")
                        .WithMany()
                        .HasForeignKey("fornecedoridForn");

                    b.Navigation("fornecedor");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.CARModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.ClienteModel", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteidCli");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.ClienteModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.EnderecoModel", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoidEnd");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.FornecedorModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.EnderecoModel", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoidEnd");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.FuncionarioModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.EnderecoModel", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoidEnd");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.OPModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.ProdutoModel", "produto")
                        .WithMany()
                        .HasForeignKey("produtoidProd");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.PedidoModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.ClienteModel", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteidCli");

                    b.HasOne("PFC_VIBRANIUM_ERP.Models.FornecedorModel", "fornecedor")
                        .WithMany()
                        .HasForeignKey("fornecedoridForn");

                    b.Navigation("cliente");

                    b.Navigation("fornecedor");
                });

            modelBuilder.Entity("PFC_VIBRANIUM_ERP.Models.ProdutoModel", b =>
                {
                    b.HasOne("PFC_VIBRANIUM_ERP.Models.EstoqueModel", "item")
                        .WithMany()
                        .HasForeignKey("itemidItem");

                    b.Navigation("item");
                });
#pragma warning restore 612, 618
        }
    }
}
